// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdoconv.h"

extern XDoconv_Config XDoconv_ConfigTable[];

XDoconv_Config *XDoconv_LookupConfig(u16 DeviceId) {
	XDoconv_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDOCONV_NUM_INSTANCES; Index++) {
		if (XDoconv_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDoconv_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDoconv_Initialize(XDoconv *InstancePtr, u16 DeviceId) {
	XDoconv_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDoconv_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDoconv_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

