// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDOCONV_H
#define XDOCONV_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdoconv_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
    u32 Kernel_bus_BaseAddress;
} XDoconv_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 Kernel_bus_BaseAddress;
    u32 IsReady;
} XDoconv;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDoconv_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDoconv_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDoconv_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDoconv_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDoconv_Initialize(XDoconv *InstancePtr, u16 DeviceId);
XDoconv_Config* XDoconv_LookupConfig(u16 DeviceId);
int XDoconv_CfgInitialize(XDoconv *InstancePtr, XDoconv_Config *ConfigPtr);
#else
int XDoconv_Initialize(XDoconv *InstancePtr, const char* InstanceName);
int XDoconv_Release(XDoconv *InstancePtr);
#endif

void XDoconv_Start(XDoconv *InstancePtr);
u32 XDoconv_IsDone(XDoconv *InstancePtr);
u32 XDoconv_IsIdle(XDoconv *InstancePtr);
u32 XDoconv_IsReady(XDoconv *InstancePtr);
void XDoconv_EnableAutoRestart(XDoconv *InstancePtr);
void XDoconv_DisableAutoRestart(XDoconv *InstancePtr);

u32 XDoconv_Get_kernel_BaseAddress(XDoconv *InstancePtr);
u32 XDoconv_Get_kernel_HighAddress(XDoconv *InstancePtr);
u32 XDoconv_Get_kernel_TotalBytes(XDoconv *InstancePtr);
u32 XDoconv_Get_kernel_BitWidth(XDoconv *InstancePtr);
u32 XDoconv_Get_kernel_Depth(XDoconv *InstancePtr);
u32 XDoconv_Write_kernel_Words(XDoconv *InstancePtr, int offset, int *data, int length);
u32 XDoconv_Read_kernel_Words(XDoconv *InstancePtr, int offset, int *data, int length);
u32 XDoconv_Write_kernel_Bytes(XDoconv *InstancePtr, int offset, char *data, int length);
u32 XDoconv_Read_kernel_Bytes(XDoconv *InstancePtr, int offset, char *data, int length);

void XDoconv_InterruptGlobalEnable(XDoconv *InstancePtr);
void XDoconv_InterruptGlobalDisable(XDoconv *InstancePtr);
void XDoconv_InterruptEnable(XDoconv *InstancePtr, u32 Mask);
void XDoconv_InterruptDisable(XDoconv *InstancePtr, u32 Mask);
void XDoconv_InterruptClear(XDoconv *InstancePtr, u32 Mask);
u32 XDoconv_InterruptGetEnabled(XDoconv *InstancePtr);
u32 XDoconv_InterruptGetStatus(XDoconv *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
