// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdoconv.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDoconv_CfgInitialize(XDoconv *InstancePtr, XDoconv_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->Kernel_bus_BaseAddress = ConfigPtr->Kernel_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDoconv_Start(XDoconv *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDoconv_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XDoconv_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDoconv_IsDone(XDoconv *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDoconv_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDoconv_IsIdle(XDoconv *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDoconv_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDoconv_IsReady(XDoconv *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDoconv_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDoconv_EnableAutoRestart(XDoconv *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDoconv_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XDoconv_DisableAutoRestart(XDoconv *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDoconv_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_AP_CTRL, 0);
}

u32 XDoconv_Get_kernel_BaseAddress(XDoconv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Kernel_bus_BaseAddress + XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE);
}

u32 XDoconv_Get_kernel_HighAddress(XDoconv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Kernel_bus_BaseAddress + XDOCONV_KERNEL_BUS_ADDR_KERNEL_HIGH);
}

u32 XDoconv_Get_kernel_TotalBytes(XDoconv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XDOCONV_KERNEL_BUS_ADDR_KERNEL_HIGH - XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + 1);
}

u32 XDoconv_Get_kernel_BitWidth(XDoconv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDOCONV_KERNEL_BUS_WIDTH_KERNEL;
}

u32 XDoconv_Get_kernel_Depth(XDoconv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDOCONV_KERNEL_BUS_DEPTH_KERNEL;
}

u32 XDoconv_Write_kernel_Words(XDoconv *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDOCONV_KERNEL_BUS_ADDR_KERNEL_HIGH - XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Kernel_bus_BaseAddress + XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XDoconv_Read_kernel_Words(XDoconv *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDOCONV_KERNEL_BUS_ADDR_KERNEL_HIGH - XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Kernel_bus_BaseAddress + XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + (offset + i)*4);
    }
    return length;
}

u32 XDoconv_Write_kernel_Bytes(XDoconv *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDOCONV_KERNEL_BUS_ADDR_KERNEL_HIGH - XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Kernel_bus_BaseAddress + XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XDoconv_Read_kernel_Bytes(XDoconv *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDOCONV_KERNEL_BUS_ADDR_KERNEL_HIGH - XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Kernel_bus_BaseAddress + XDOCONV_KERNEL_BUS_ADDR_KERNEL_BASE + offset + i);
    }
    return length;
}

void XDoconv_InterruptGlobalEnable(XDoconv *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDoconv_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_GIE, 1);
}

void XDoconv_InterruptGlobalDisable(XDoconv *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDoconv_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_GIE, 0);
}

void XDoconv_InterruptEnable(XDoconv *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDoconv_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_IER);
    XDoconv_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XDoconv_InterruptDisable(XDoconv *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDoconv_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_IER);
    XDoconv_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XDoconv_InterruptClear(XDoconv *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDoconv_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XDoconv_InterruptGetEnabled(XDoconv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDoconv_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_IER);
}

u32 XDoconv_InterruptGetStatus(XDoconv *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDoconv_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XDOCONV_CTRL_BUS_ADDR_ISR);
}

